"""
AnalystAgent — Research and signal generation agent.

The AnalystAgent reads market data, performs technical/fundamental analysis,
and generates trading signals. It operates within the OpenClaw agent mesh
and is bounded by the IntentContract.

Allowed tools (typical):
    - market_data: Read market data and prices
    - get_position: Check current portfolio positions

NOT allowed:
    - place_order: Analyst cannot trade
    - Any tool not explicitly listed in the IntentContract
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from grid.enforcement_gate import EnforcementGate
from grid.policy_engine import ActionRequest


class MarketSignal:
    """A trading signal generated by the analyst."""
    
    def __init__(
        self,
        ticker: str,
        signal_type: str,
        strength: float,
        reasoning: str,
        price: float,
        metadata: Optional[Dict] = None,
    ):
        self.signal_id = str(uuid.uuid4())
        self.ticker = ticker
        self.signal_type = signal_type  # "buy", "sell", "hold"
        self.strength = strength  # 0.0 to 1.0
        self.reasoning = reasoning
        self.price = price
        self.metadata = metadata or {}
        self.generated_at = datetime.now(timezone.utc).isoformat()
    
    def to_dict(self) -> Dict:
        return {
            "signal_id": self.signal_id,
            "ticker": self.ticker,
            "signal_type": self.signal_type,
            "strength": self.strength,
            "reasoning": self.reasoning,
            "price": self.price,
            "metadata": self.metadata,
            "generated_at": self.generated_at,
        }
    
    def __repr__(self):
        return f"MarketSignal({self.ticker} {self.signal_type} strength={self.strength:.2f})"


class AnalystAgent:
    """
    Research and signal generation agent for the GRID agent mesh.
    
    The AnalystAgent operates in the research layer — it reads market data
    and generates signals, but cannot execute trades. All data access
    requests go through the EnforcementGate.
    
    Compatible with OpenClaw's agent orchestration framework.
    
    Example:
        >>> analyst = AnalystAgent(gate, agent_id="analyst_001")
        >>> signals = analyst.analyze("AAPL")
        >>> for signal in signals:
        ...     print(f"{signal.ticker}: {signal.signal_type} ({signal.strength:.0%})")
    """
    
    ROLE = "analyst"
    
    def __init__(
        self,
        gate: EnforcementGate,
        agent_id: Optional[str] = None,
    ):
        """
        Initialize the AnalystAgent.
        
        Args:
            gate: EnforcementGate for policy-gated execution.
            agent_id: Unique agent identifier (auto-generated if None).
        """
        self.agent_id = agent_id or f"analyst_{uuid.uuid4().hex[:8]}"
        self.gate = gate
        self._signals: List[MarketSignal] = []
    
    def analyze(self, ticker: str, current_price: Optional[float] = None) -> List[MarketSignal]:
        """
        Analyze a ticker and generate trading signals.
        
        First requests market data access through the gate, then performs
        analysis if access is granted.
        
        Args:
            ticker: Ticker symbol to analyze.
            current_price: Current price (simulated for demo).
            
        Returns:
            List of MarketSignal objects.
        """
        # Request market data access through the gate
        data_request = ActionRequest(
            agent_id=self.agent_id,
            agent_role=self.ROLE,
            action_type="tool_use",
            tool_name="market_data",
            ticker=ticker,
        )
        
        result = self.gate.process(data_request)
        
        if not result.allowed:
            print(f"  [AnalystAgent] ❌ Market data access BLOCKED for {ticker}")
            print(f"  Reason: {result.policy_result.block_reasons}")
            return []
        
        print(f"  [AnalystAgent] ✅ Market data access granted for {ticker}")
        
        # Simulated analysis (in production, would use real market data)
        price = current_price or self._simulated_price(ticker)
        signals = self._generate_signals(ticker, price)
        
        self._signals.extend(signals)
        return signals
    
    def _simulated_price(self, ticker: str) -> float:
        """Get simulated price for demo purposes."""
        prices = {
            "AAPL": 172.50,
            "GOOGL": 141.80,
            "MSFT": 415.20,
            "NVDA": 878.40,
            "TSLA": 175.30,
            "AMZN": 178.90,
            "META": 505.60,
        }
        return prices.get(ticker.upper(), 100.0)
    
    def _generate_signals(self, ticker: str, price: float) -> List[MarketSignal]:
        """
        Generate trading signals based on analysis.
        
        Uses simulated technical analysis for demo. In production,
        this would integrate with real TA libraries and LLM reasoning.
        """
        signals = []
        
        # Simulated momentum signal
        signals.append(MarketSignal(
            ticker=ticker,
            signal_type="buy",
            strength=0.75,
            reasoning=(
                f"Technical analysis indicates {ticker} is showing strong upward momentum. "
                f"RSI at 58 (not overbought), MACD bullish crossover detected. "
                f"Current price ${price:.2f} is above 50-day SMA."
            ),
            price=price,
            metadata={
                "indicator": "momentum",
                "rsi": 58.3,
                "macd_signal": "bullish_crossover",
                "sma_50_position": "above",
            }
        ))
        
        return signals
    
    def get_latest_signals(self, ticker: Optional[str] = None) -> List[MarketSignal]:
        """
        Retrieve latest signals, optionally filtered by ticker.
        
        Args:
            ticker: Optional ticker to filter by.
            
        Returns:
            List of MarketSignal objects.
        """
        if ticker:
            return [s for s in self._signals if s.ticker == ticker.upper()]
        return self._signals
    
    def clear_signals(self):
        """Clear all stored signals."""
        self._signals.clear()
    
    def __repr__(self):
        return f"AnalystAgent(id={self.agent_id}, signals={len(self._signals)})"
